site_name: Homepage
site_author: Junyi Yang
site_url: https://rebelice.github.io/homepage

theme:
  name: 'material'
  palette:
    primary: 'Brown'
    accent: 'Deep Orange'
  logo:
    icon: 'label'
  favicon: 'images/favicon.ico'
  feature:
    tabs: true

extra:
  social:
    - type: 'github'
      link: 'https://github.com/rebelice'

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true